[package]
name = "rust-sql-server"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.1"
sqlparser = "0.39.0"

[[bin]]
name = "rsqld"
path = "src/sqld.rs"
